const builderPageSelectors = {
    qlEditor: '.ql-editor',
    BuildersQuillForm:'BuildersQuillForm',
    saveAndNextButton:"//button[normalize-space()='save + next >']",
    myEvent:'button.sideNav__link--myevents',
    qlVideo:'.ql-video',
    qlAction:'.ql-action',
    saveButton:'.answer__save-btn',
    titleTextbox:'[name="title"]',
    companySchoolTextbox:'[name="organization_name"]',
    topicMainLink:'.topic-main__link',
    finishButton:'a > .btn-main',
    projectBuilderLink:'//span[text()="Project Builders"]',
    projectPageLink:'//span[text()="Project Page"]',
    solutionLink:"(//h4[contains(text(),'Solution')])[1]",
    revisitButton:'.overview__topic-box:nth-child(2) .overview__topic-box__flex > .overview__topic-box__btn--visited',
    skipAnswerButton:"//a[normalize-space()='skip to answer >']",
    strikeButton:'button.ql-strike',
    qlEditorImageButton:'.ql-image > svg > .ql-even',
    toolTipInput:'.ql-tooltip > input',
    saveAnswerButton:'.react-confirm-alert-button-group > :nth-child(1)',
    strokeButton:'.ql-image > svg > .ql-stroke',
    videoIcon:'.ql-video > svg',
    gotItNextButton:'//button[text()="Got it, next"]',
    switchTrackButton:'//button[text()="switch tracks"]',
    revisitButton:'//a[text()="Revisit"]',
    stepMenuRightSide:':nth-child(2) > .intro__sideNav__expand > .intro__sideNav__expand__label',
    nextButton:'//button[normalize-space()="Next >"]',
    minimizeButton:'.rebelMap__btn--minimize',
    reviewPublishButton:' //a[text()="Review + Publish"]',
    publishDropdown:'label.sidebar__published__drpdwn',
    publishItem:'//button[text()="edit publish settings"]',
    goButton:' //a[text()="Go >"]',
}
export { builderPageSelectors }