const hubActivityPageSelector ={
    pageTitle:'.createHub__title',
    descriptionTextbox:'.createHub__description',
    saveButton:"//button[contains(text(),'Save')]",
    editLink:'.edit-link',
    roleTitleTextbox:'input[name="role_title"]',
    selectAnnouncment:"//h3[contains(text(),'Announcement')]",
    stickyCheckbox:'#dialog__sticky__check',
    announceButton:"//button[contains(text(),'announce')]",
    addYourThought:"//button[contains(text(),'Add your thoughts')]",
    cancelButton:'//button[text()="Cancel"]',
    selectPost:"//h3[contains(text(),'Post')]",
    selectQuestion:"//h3[contains(text(),'Question')]",
    questionTitle:'input[name="question"]',
    askButton:"//button[contains(text(),'ask')]",
    answerButton:'//*[text()="0 Answers"]',
    postButton:'//*[text()="Post"]',
    replyButton:'//*[text()="Reply"]',
    upVoteAnswer:'[data-testid="KeyboardArrowUpIcon"]',
    selectOffer:"//h3[contains(text(),'Offer')]",
    offerButton:'//button[text()="Offer"]',
    bellIcon:'[aria-label="Invites"]',
    selectIdea:"//h3[contains(text(),'Idea')]",
}
export {hubActivityPageSelector}