const eventPageSelectors = {
    pageTitle:'.ePage__title__name',
    compititor:"//h6[normalize-space()='Competitors']",
    seeAllLink:"//*[contains(text(),'see all')]",
    inviteButton:'//button[text()="invite"]',
    inviteTopersonalize:'.invite-to-hub__personalize',
    noButton:"//button[contains(text(),'No')]",
    yesButton:"//button[contains(text(),'Yes')]",
    updateEventButton:"//button[contains(text(),'Update Event')]",
    editPen:'.edit-pen',
    descriptionField:'[name="description"]',
    sponserNameTextbox:'[name="sponsor_name"]',
    sponsorWebsiteTextbox:'[name="sponsor_website"]',
    fileType:'input[type="file"]',
    addSponsorButton:"//button[contains(text(),'Add Sponsor')]",
    postTextbox:'[placeholder="speak your mind here..."]',
    postButton:"//button[contains(text(),'post')]",
    stickyCheckbox:'.checkbox',
    eventTodate:'#rw_7_input',
    sponsorPlusButton:'.plus-sign',
    roundOne:'//li[text()="Round 1"]',
    startRoundButton:"//button[normalize-space()='start this round']",
    selectProjectButton:"//button[normalize-space()='select project']",
    editYourBioButton:"//*[text()='edit your bio']",
    bioTitle:"input[placeholder='title']",
    bioDescription:'textarea[name="bio"]',
    updateButton:"//button[contains(text(),'update')]",
    inviteParticipentButton:"//button[contains(text(),'Invite Participants')]",
    submitButton:"//button[contains(text(),'Submit')]",
    selectType:'[name="event_type"]',
    submitMyProjectButton:"//button[contains(text(),'submit my project')]",
    allMyEventLink:"//button[contains(text(),'All My Events')]",
    changeProjectButton:"//button[normalize-space()='change project']",
    roundModelPopupHeading:'.scoring__edit > :nth-child(1)',
    openRoundButton:"//button[contains(text(),'open this round!')]",
    doneButton:"//button[contains(text(),'done')]",
    saveAndLeaveButton:"//button[contains(text(),'Save and Leave')]",
    backLink:'.back-link',
    editYourEvaluationButton:'(//button[normalize-space()="edit your evaluation"])[1]',
    closeThisRound:"//button[contains(text(),'close this round')]",
    reOpenRoundButton:"//button[contains(text(),'re-open round')]",
    publishScoreButton:"//button[contains(text(),'publish scores')]",
    awardTab:'//li[text()="Awards"]',
    selectAwardButton:"//button[contains(text(),'select award')]",
    yesSubmitButton:"//button[contains(text(),'Yes, submit')]",
}
export {eventPageSelectors}