const smokeTestPageSelector = {
    emailTextbox: "//input[@name='email']",
    passwordTextbox: "//input[@name='password']",
    loginButton: "button[type='submit']",
    addProjectButton: '[aria-label="add project"]',
    projectNameTextbox: '[placeholder="Project or Company Name"]',
    autoCompleteTextbox: '#-google-places-autocomplete-input',
    locationResultInput: '#-google-places-autocomplete-suggestion--0',
    industryDropdown: '[name="industry_id"]',
    createButtom: '//button[normalize-space()="create >"]',
    projectHeader: '.index-header__projName',
    inviteEmailTextbox: '.inviteForm [name="email"]',
    sendInviteButton: "//button[contains(text(),'Send invite')]",
    devHub: ':nth-child(2) > .MuiList-root > .MuiButtonBase-root',
    groupLink: "//span[contains(text(),'Groups')]",
    activityLink: "//span[contains(text(),'Activities')]",
    eventLink: "//span[contains(text(),'Events')]",
    addGroupButton: '.group-overview__add-btn',
    groupNameTextbox: '[placeholder="Name of Group *"]',
    selectAllButton: "//span[contains(text(),'select all')]",
    createGroupButton: "//button[contains(text(),'create group')]",
    groupHeading: '[data-testid=group_name]',
    searchBar: '.search-input',
    projectHover: ':nth-child(1) > div.group-overview__title-wrap > div > div > button:nth-child(2)',
    deleteButtom: "//div[@class='ReactModalPortal']//button[contains(text(),'Delete')]",
    post: "//button[@type='button']//h3[contains(text(),'Post')]",
    postTextbox: 'textarea[name="details"]',
    postButton: "//div[@class='dialog']//button[contains(text(),'Post')]",
    newEventButton: "//button[contains(text(),'New Event')]",
    eventNameTextbox: '[placeholder="Add event name *"]',
    fromDate: '#rw_1_input',
    fromTime: '#rw_2_input',
    toDate: '#rw_3_input',
    toTime: '#rw_4_input',
    yesButton: "//label[contains(text(),'Yes')]",
    headerDropdown: '[data-testid=ArrowDropDownIcon]',
    logoutButton: '[data-testid=LogoutIcon]',
    signUpFirstName: '[name="firstName"]',
    signUpLastName: '[name="lastName"]',
    signUpEmail: '[name="email"]',
    signUpPassword: '[name="password"]',
    signUpConfirmPassword: '[name="confirmPassword"]',
    getStartedButton: "//button[normalize-space()='Get Started >']",
    readyButton: "//button[contains(text(),'READY!')]",
}
export { smokeTestPageSelector }